# Generated by Django 4.2.3 on 2023-07-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
