# Generated by Django 4.2.3 on 2023-07-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Gold', 'Gold'), ('Copper', 'Copper'), ('Silver', 'Silver'), ('Brown', 'Brown')], default='Black', max_length=50),
        ),
    ]
