# Generated by Django 4.2.3 on 2023-07-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='jewelrytype',
            field=models.CharField(choices=[('Necklace', 'Necklace'), ('Bracelet', 'Bracelet'), ('Ring', 'Ring'), ('Earring', 'Earring'), ('Anklet', 'Anklet'), ('Hairclip', 'Hairclip')], default='necklace', max_length=50),
        ),
    ]
